(function(g){var window=this;'use strict';var $3=function(a){g.U.call(this,{G:"div",L:"ytp-inline-preview-ui"});this.ye=!1;this.player=a;this.T(a,"onStateChange",this.bI);this.T(a,"videodatachange",this.Hl);this.T(a,"onInlinePreviewModeChange",this.iV);this.Xd=new g.zp(this.Nq,null,this);g.I(this,this.Xd)},a4=function(a){g.BL.call(this,a);
this.j=new $3(this.player);g.I(this,this.j);this.j.hide();g.oL(this.player,this.j.element,4);a.isInline()&&(this.load(),g.L(a.getRootNode(),"ytp-inline-preview-mode",!0),this.player.U().S("web_inline_player_disable_scrubbing")&&g.L(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0))};
g.v($3,g.U);g.h=$3.prototype;
g.h.NF=function(){this.tooltip=new g.yP(this.player,this);g.I(this,this.tooltip);g.oL(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.yc=new g.wM(this.player);g.I(this,this.yc);var a=["ytp-inline-preview-scrim"];this.player.U().S("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.Mg=new g.U({G:"div",Ha:a});g.I(this,this.Mg);this.Mg.Ba(this.element);this.T(this.Mg.element,"click",this.nB);this.player.U().S("web_inline_player_expand_to_watch")&&(a=new g.y_(this.player,
this),g.I(this,a),a.Ba(this.Mg.element));this.Pg=new g.kP(this.player,this);g.I(this,this.Pg);this.Pg.Ba(this.Mg.element);this.controls=new g.U({G:"div",L:"ytp-inline-preview-controls"});g.I(this,this.controls);this.controls.Ba(this.element);a=new g.TN(this.player,this);g.I(this,a);a.Ba(this.controls.element);a=new g.iP(this.player,this);g.I(this,a);a.Ba(this.controls.element);this.Ic=new g.gO(this.player,this);g.I(this,this.Ic);g.oL(this.player,this.Ic.element,4);this.T(this.player,"appresize",this.yb);
this.T(this.player,"fullscreentoggled",this.yb);this.yb()};
g.h.show=function(){g.Ap(this.Xd);this.ye||(this.NF(),this.ye=!0);0!==this.player.getPlayerState()&&g.U.prototype.show.call(this);this.Ic.show()};
g.h.hide=function(){this.Xd.stop();g.U.prototype.hide.call(this);this.player.isInline()||this.ye&&this.Ic.hide()};
g.h.ra=function(){g.U.prototype.ra.call(this)};
g.h.nB=function(a){a.target!==this.Mg.element||this.player.U().S("web_inline_player_expand_to_watch")||this.player.Qa("onExpandInlinePreview",a)};
g.h.iV=function(){g.L(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.h.Fd=function(){this.Ic.Qb();this.Pg.Qb()};
g.h.Nq=function(){this.Fd();g.Ap(this.Xd)};
g.h.yb=function(){g.wO(this.Ic,0,this.player.gb().getPlayerSize().width,!1);g.jO(this.Ic)};
g.h.bI=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.h.Hl=function(a,b){this.player.isInline()&&g.L(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.iH)};
g.h.pc=function(){return this.tooltip};
g.h.Ze=function(){return!1};
g.h.Df=function(){return!1};
g.h.Ki=function(){return!1};
g.h.Zx=function(){};
g.h.Qn=function(){};
g.h.Vs=function(){};
g.h.zo=function(){return null};
g.h.Gw=function(){return null};
g.h.Hj=function(){return new g.Pm(0,0,0,0)};
g.h.handleGlobalKeyDown=function(){return!1};
g.h.handleGlobalKeyUp=function(){return!1};
g.h.Uq=function(a,b,c,d,e){var f=d=0,k=0,l=g.en(a);if(b){c=g.Hp(b,"ytp-miniplayer-expand-watch-page-button");var m=g.Hp(b,"ytp-mute-button"),n=g.Hp(b,"ytp-subtitles-button"),p=g.cn(b,this.element);b=g.en(b);d=p.y+40;c&&(k=8);if(n||m)k=p.x-l.width+b.width}else k=c-l.width/2,f=35;b=this.player.gb().getPlayerSize().width;k=g.zh(k,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=k+"px"};
g.h.showControls=function(){};
g.h.Fl=function(){};
g.h.Vk=function(){return!1};g.v(a4,g.BL);a4.prototype.Zh=function(){return!1};
a4.prototype.load=function(){this.player.hideControls();this.j.show()};
a4.prototype.unload=function(){this.player.showControls();this.j.hide()};g.AL("inline_preview",a4);})(_yt_player);
